Makes ITUserRestrictedDTO more restricted
cthit/Gamma pull request #767
Opened 2020-08-29 17:01 UTC by Portals

2020-08-29 17:11 UTC, SantaPoro approved these changes

2020-09-01 11:11 UTC, Gurr1 approved these changes
Looked through and tested it, found nothing to complain about

Good work :)

A bit unsure if this will break bookIT emails

2020-09-01 11:35 UTC, Gurr1 requested changes
Just tested this, it will break bookIT

wait until https://github.com/cthit/bookIT/pull/94 is merged before merging this

2020-09-21 11:26 UTC, Gurr1 approved these changes

2020-09-21 15:20 UTC, Swexbe commented
Merging by request of @Portals

2020-09-21 15:20 UTC, merged